server:
  port: 5000
spring:
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
  security:
    oauth2:
      client:
        registration:
          github: 
            client-id: 2c9cb10c3a1d037685d9
            client-secret: adb115f3ba48585a236998d7c75b59c8da66402f
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
                - user:email
                - read:user
    provider: 
      github:  
        authorization-uri: https://github.com/login/oauth/authorize 
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user 


    